-- https://programmers.co.kr/learn/courses/30/lessons/59405
-- ORACLE

WITH
rnk AS (
SELECT
    NAME,
    ROW_NUMBER() OVER(ORDER BY DATETIME) AS RANK
FROM ANIMAL_INS
)
SELECT NAME
FROM rnk
WHERE rank = 1
;

SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
FETCH FIRST 1 ROW ONLY
;

SELECT NAME
FROM (SELECT NAME
      FROM ANIMAL_INS
      ORDER BY DATETIME)
WHERE ROWNUM = 1
;

SELECT MIN(NAME) KEEP(DENSE_RANK FIRST ORDER BY DATETIME) AS NAME
FROM ANIMAL_INS
;