-- https://programmers.co.kr/learn/courses/30/lessons/59412
-- ORACLE

WITH
TMP AS (
SELECT
    TO_CHAR(DATETIME, 'HH24') AS HOUR
FROM ANIMAL_OUTS
)
SELECT
    HOUR,
    COUNT(*) AS COUNT
FROM TMP
WHERE HOUR BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY 1
;

SELECT
    TO_CHAR(DATETIME,'HH24') AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19 
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY 1
;