-- https://programmers.co.kr/learn/courses/30/lessons/59042
-- ORACLE

SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_INS I
    RIGHT JOIN ANIMAL_OUTS O
    ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY 1
;

SELECT
    ANIMAL_ID,
    NAME 
FROM ANIMAL_OUTS
    MINUS
SELECT 
    ANIMAL_ID,
    NAME
FROM ANIMAL_INS
ORDER BY 1
;